### ISSUE TITLE
Failed to download geolocation database

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#127]
Whenever I run stig, I get this error:

```
Failed to download geolocation database https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz: Unknown error -2
```

It started happening today, Jan 14th.

Have upgraded maxminddb to latest version 1.5.2 but the error persists.

Running latest master, 49b864f, on Xubuntu 18.04.03.

**Comment by rndusr** [comment]
Sorry, that's a bad error message. It should say that the host name can't be
resolved.

Anyway, Maxmind requires an account to download free DBs now:
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by marcelpaulo** [comment]
Creating a Maxmind account and configuring a _GeoIP.conf_ to use the credentials will be enough?

In case I want to stop using geolocation, removing the Python module _maxminddb_ will do the trick?

**Comment by rndusr** [comment]
Everything I know about this issue is in that blog post. The burden of creating
an account should probably be on me, but I haven't really looked into it.

Another fix would be to get country codes from the online API, but I don't
really like that for privacy reasons.

You can disable geolocation with the "geoip" setting:

    set geoip off

**Comment by marcelpaulo** [comment]
> set geoip off

It will be for now. Thanks!

**Comment by marcelpaulo** [comment]
Now I have `set geoip off` in _~/.config/stig/rc_. If I run `stig` interactively, the error doesn't pop up and I can see that the country codes are not pulled. But if I run `stig add` to add a torrent, I still get the same error, for instance, just for testing:

```
paulo:~/prj/torr/test (master)$ stig add Lambs.of.God.S01E01.WEBRip.x264-ION10.torrent
Failed to download geolocation database https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz: Unknown error -2
add: Added Lambs.of.God.S01E01.WEBRip.x264-ION10
```

Here's my _rc_:

```
set columns.torrents marked,size,downloaded,uploaded,ratio,seeds,peers,status,eta,%downloaded,activity,rate-down,rate-up,name

tab ls --sort !%downloaded,status all
tab ls complete
tab ls downloading
tab --focus 0

set unit.bandwidth bit

bind d tab --close --focus left

set geoip off
```

**Comment by marcelpaulo** [comment]
The only way to stop the error from happening when running CLI `stig` was uninstalling _maxminddb_ altogether.

**Comment by rndusr** [comment]
The rc commands should always be run before any CLI commands.

Try enabling debugging messages like this:

    stig --debug '' --debug-file debug.log add Lambs.of.God.S01E01.WEBRip.x264-ION10.torrent

Then post the relevant lines (or the whole thing if you're lazy).

Another easy fix for this would be:

    touch ~/.cache/stig/GeoLite2-Country.mmdb

This should set the creation date of the file to "now" and stig will think the
file is recent enough for another 30 days.

**Comment by marcelpaulo** [comment]
> stig --debug '' --debug-file debug.log add Lambs.of.God.S01E01.WEBRip.x264-ION10.torrent

```
06:29:14.218: [settings.rcfile] Reading rc file: '/home/paulo/.config/stig/rc'
06:29:14.218: [commands.guess_ui] Guessing whether TUI or CLI is wanted:
06:29:14.218: [commands] turned [['add', 'Lambs.of.God.S01E01.WEBRip.x264-ION10.torrent']] into [['add', 'Lambs.of.God.S01E01.WEBRip.x264-ION10.torrent']]
06:29:14.218: [commands] Parsed command chain: [['add', 'Lambs.of.God.S01E01.WEBRip.x264-ION10.torrent']]
06:29:14.219: [commands.guess_ui]   add: torrent command - guessing CLI
06:29:14.219: [commands.guess_ui] Guessed wanted UI: cli
06:29:14.219: [client.geoip] Cached database is 2770251.678767681 seconds old
06:29:14.219: [client.geoip] Fetching fresh geolocation database from https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz
06:29:14.365: [client.geoip] Calculating minimum delay between downloads: min(1 * 2, 3600)
06:29:14.366: [client.geoip] New minimum delay between downloads: 2 seconds
Failed to download geolocation database https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz: Unknown error -2
```

It looks like it's checking the geoip db before running the rc commands.

**Comment by rndusr** [comment]
That's really weird. I can't reproduce this. For me, your rc file runs "set
geoip false" before the "add" command.

I'm also using latest master.

I've tried this several times so it doesn't seem to be a race condition.

**Comment by rndusr** [comment]
I've "solved" this issue by removing geoip support.
